[package]
name = "bevy-gp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'

[dependencies]
bevy = "0.9.1"
vec3 = "0.2.1"
